language: node_js
node_js: --lts
before_script:
  - git config user.name "qcminecraft"
  - git config user.email "qcmc@qcminecraft.com"
    - sed -i "s/gh_token/${GH_TOKEN}/g" ./_config.yml
script:
  - hexo g
  - hexo d
