language: node_js
node_js:
  - '10'

branches:
  only:
  - master

before_install:
- git config --global user.name "AUTOBUILD"
- git config --global user.email "nyaruko@pm.me"
- sed -i'' "s~https://github.com/oieasy/lc_posts.git~https://3c6f62b19635fe6757a16debc7ddc3f66df58a0d@github.com/oieasy/lc_posts.git~" _config.yml

install:
- npm install hexo-cli -g
- npm install

script:
- npm run deploy
