# 指定语言环境
language: node_js
# 指定需要sudo权限
sudo: required
# 指定node_js版本
node_js: 
  - 10
before_install:
  - npm install -g hexo-cli

# Start: Build Lifecycle
install:
  - npm install hexo-deployer-git --save
  - rm package-lock.json
  - npm cache clear --force
  - npm install -f

script:
  - hexo g

# 设置git提交名，邮箱；替换真实token到_config.yml文件，最后depoy部署
after_script:
  - git config user.name "AUTOBUILD"
  - git config user.email "nyaruko@pm.me"
  - sed -i'' "s~_token_~${GH_TOKEN}~" _config.yml
  - hexo d
# End: Build LifeCycle
